---
title: "Homework 6"
author: "Mukta Patwari"
date: "2025-11-11"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

Loading the homicide data

```{r}
library(readr)

homicide_data =
  read_csv("homicide-data.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    city_state = str_c(city, state, sep = ", "),
    solved = factor(
  case_when(
    disposition %in% c("Closed without arrest", "Open/No arrest") ~ "Unsolved",
    TRUE ~ "Resolved"),
  levels = c("Unsolved", "Resolved"))
  ) %>% 
  filter(
    !city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"),
    victim_race %in% c("White", "Black")
  ) %>% 
  mutate(
    victim_age = as.numeric(victim_age)
  )
```

Odds ratios for Baltimore

```{r}
baltimore_df =
  homicide_data %>% 
  filter(city_state == "Baltimore, MD")

baltimore_fit =
  baltimore_df %>% 
  glm(
    formula = solved ~ victim_age + victim_sex + victim_race,
    data = .,
    family = binomial
  ) 

baltimore_fit %>% 
  broom::tidy(conf.int = TRUE) %>% 
  mutate(
    OR = exp(estimate), 
    OR_conf_low = exp(conf.low), 
    OR_conf_high = exp(conf.high)) %>%
  filter(term == "victim_sexMale") %>%
  select(term, OR, OR_conf_low, OR_conf_high) %>% 
  knitr::kable(digits = 3)
```

Odds ratios for all cities

```{r}
cities_fit =
  homicide_data %>%
  group_by(city_state) %>%
  nest() %>%
  mutate(
    fit = map(data, ~ glm(
      solved ~ victim_age + victim_sex + victim_race,
      data = .x,
      family = binomial
    )),
    
    tidy = map(fit, ~ 
      broom::tidy(.x, conf.int = TRUE) %>%
        mutate(
          OR = exp(estimate),
          OR_conf_low = exp(conf.low),
          OR_conf_high = exp(conf.high)
        ) %>%
        filter(term == "victim_sexMale") %>%
        select(term, OR, OR_conf_low, OR_conf_high)
    )
  ) %>%
  unnest(tidy)
```

Plot

```{r}
cities_fit %>%
  arrange(OR) %>%
  mutate(city_state = factor(city_state, levels = city_state)) %>%
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = OR_conf_low, ymax = OR_conf_high), width = 0.2) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(
    title = "Adjusted Odds Ratios for Solved Homicides",
    x = "City",
    y = "Adjusted Odds Ratio (Male vs Female)"
  )
```

